== Requirements

* https://packer.io[Packer].
* https://www.docker.com/[Docker].

=== Suggested requirements

* The `realpath` command-line utility, e.g. the https://www.gnu.org/software/coreutils/manual/html_node/realpath-invocation.html[GNU coreutils one].
* The `tac` command-line utility, also offered by GNU coreutils.

== To build

* Clone this repository (once).
* `cd` to its root directory.
* Retrieve the submodules under `resources/` (once):
+
[source,Sh]
----
git submodule update --init --recursive
----
* Build the dependency https://github.com/clarin-eric/SPF_SAML_metadata_processor[`SPF_SAML_metadata_processor`].
* To pull in the latest versions (on the `master` branch) of the submodules, issue:
+
[source,Sh]
----
git submodule update --recursive --remote
----
* To build the virtualized application up from all Docker container images it depends on, issue (once per shell session):
+
[source,Sh]
----
build_all() {
    set -e
    for packer_file in $(find . $(git submodule --quiet foreach --recursive 'pwd') -maxdepth '1' -type 'f' -name 'packer.json' | tac)
    do
        set -x
        packer build "${packer_file}"
        set +x
    done
    set +e
}
----
+
* From then on you may issue (as long as your current working directory mentioned in the first steps is still correct) `build_all ;` to start the build.

== To run

* First make sure your current working directory is the root directory of your local copy of this repository, and that the previously described build process has completed successfully.
* Next, if it hasn't been imported yet, import the Docker container image. E.g. issue:
+
[source,Sh]
----
docker import - 'docker.clarin.eu/alpine-python_3-spf_saml_metadata_processing:latest' < 'images/latest.tar'
----

=== ... interactively
Issue:
+
[source,Sh]
----
docker run -v $(realpath resources/pyff_config/)':/srv/pyff_config/' -i -t --entrypoint='/bin/sh' 'docker.clarin.eu/alpine-python_3-spf_saml_metadata_processing'
----

////

TODO:
Packer should not rebuild artifacts.
document pyff
-v (realpath resources/SAML_metadata_QA_validator/)':/opt/SAML_metadata_QA_validator/:ro'
/opt/SAML_metadata_QA_validator/

=== detachedly

[source,Sh]
----

----
////
